const express = require('express')
const {getAllProducts,createProduct,ProductsUpdate, DeleteProduct, ProductDetails}=require('../controller/ProductController')
const { isAuthenticated,authorizedRoles } = require('../middleware/auth')
const router=express.Router()
router.route('/products').get(getAllProducts)
router.route('/product/new').post(isAuthenticated,authorizedRoles("admin"),createProduct)
router.route('/product/update/:id').put(isAuthenticated,authorizedRoles("admin"),ProductsUpdate)
.delete(isAuthenticated,authorizedRoles("admin"),DeleteProduct)
.get(isAuthenticated,ProductDetails)
module.exports=router