const express = require('express')
const { isAuthenticated,authorizedRoles } = require('../middleware/auth')
const { registerUser, loginUSer, logout, forgetpassword, resetpassword, getUserDetails, UpdateUserProfile, getAlluser } = require('../controller/userController')
const router = express.Router()
router.route("/register").post(registerUser)
router.route("/login").post(loginUSer)
router.route("/logout").get(logout)
router.route("/password/forget").post(forgetpassword)
router.route("/password/reset/:token").put(resetpassword)
router.route("/me/details").get(isAuthenticated,getUserDetails)
router.route("/me/details/update").put(isAuthenticated,UpdateUserProfile)
router.route("admin/all/user").get(isAuthenticated,authorizedRoles("admin"),getAlluser)
module.exports = router  